-- MySQL Script generated by MySQL Workbench
-- Wed Aug 27 12:49:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `LocationId` BIGINT NOT NULL,
  `Longitude` DECIMAL(7,4) NOT NULL,
  `Latitude` DECIMAL(7,4) NOT NULL,
  PRIMARY KEY (`LocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cafe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cafe` (
  `CafeId` SMALLINT NOT NULL,
  `CafeName` VARCHAR(70) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  `LocationId` INT NOT NULL,
  `OpeningHours` TEXT NOT NULL,
  PRIMARY KEY (`CafeId`),
  INDEX `fk_Cafe_Location1_idx` (`LocationId` ASC) VISIBLE,
  CONSTRAINT `fk_Cafe_Location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drink` (
  `DrinkId` TINYINT NOT NULL,
  `DrinkName` VARCHAR(70) NOT NULL,
  `DrinkDescription` VARCHAR(255) NULL,
  PRIMARY KEY (`DrinkId`),
  UNIQUE INDEX `DrinkId_UNIQUE` (`DrinkId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `Brew` VARCHAR(45) NULL,
  `Gender` ENUM('male', 'female', 'unknowm') NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Drink1_idx` (`Brew` ASC) VISIBLE,
  CONSTRAINT `fk_User_Drink1`
    FOREIGN KEY (`Brew`)
    REFERENCES `mydb`.`Drink` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Drink2`
    FOREIGN KEY (`Brew`)
    REFERENCES `mydb`.`Drink` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo` (
  `idPhoto` INT NOT NULL,
  PRIMARY KEY (`idPhoto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620
COLLATE = tis620_bin;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `PostId` BIGINT NOT NULL,
  `PostText` VARCHAR(1000) NOT NULL,
  `PostPhoto` BLOB NULL,
  `PostTime` DATETIME NOT NULL,
  PRIMARY KEY (`PostId`),
  UNIQUE INDEX `PostId_UNIQUE` (`PostId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BrewHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BrewHistory` (
  `BrewHistoryId` INT NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `CustomerId` INT NOT NULL,
  `DrinkId` INT NOT NULL,
  PRIMARY KEY (`BrewHistoryId`),
  INDEX `fk_BrewHistory_Drink2_idx` (`DrinkId` ASC) VISIBLE,
  INDEX `fk_BrewHistory_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  UNIQUE INDEX `BrewHistoryId_UNIQUE` (`BrewHistoryId` ASC) VISIBLE,
  CONSTRAINT `fk_BrewHistory_Drink2`
    FOREIGN KEY (`DrinkId`)
    REFERENCES `mydb`.`Drink` (`DrinkId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BrewHistory_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LikePostHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LikePostHistory` (
  `idLikePost` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idPost` INT NOT NULL,
  `setDate` DATE NOT NULL,
  PRIMARY KEY (`idLikePost`),
  INDEX `fk_LikePost_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_LikePost_Post1_idx` (`idPost` ASC) VISIBLE,
  CONSTRAINT `fk_LikePost_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LikePost_Post1`
    FOREIGN KEY (`idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620
COLLATE = tis620_bin;


-- -----------------------------------------------------
-- Table `mydb`.`CommentPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommentPost` (
  `idCommentPost` INT NOT NULL,
  `idPost` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCommentPost`),
  INDEX `fk_CommentPost_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_CommentPost_Post1_idx` (`idPost` ASC) VISIBLE,
  CONSTRAINT `fk_CommentPost_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CommentPost_Post1`
    FOREIGN KEY (`idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620
COLLATE = tis620_bin;


-- -----------------------------------------------------
-- Table `mydb`.`CurrentLocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CurrentLocation` (
  `CurrentLocationId` BIGINT NOT NULL,
  `CustomerId` INT NOT NULL,
  `LocationId` BIGINT NOT NULL,
  `CurrentTime` DATETIME NOT NULL,
  `BeepStatus` CHAR(1) NOT NULL,
  INDEX `fk_CurrentLocation_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_CurrentLocation_Location1_idx` (`LocationId` ASC) VISIBLE,
  PRIMARY KEY (`CurrentLocationId`),
  UNIQUE INDEX `CurrentLocationId_UNIQUE` (`CurrentLocationId` ASC) VISIBLE,
  CONSTRAINT `fk_CurrentLocation_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CurrentLocation_Location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FollowHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FollowHistory` (
  `idFollow` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idFollower` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Status` ENUM('follow', 'unfollow') NOT NULL,
  PRIMARY KEY (`idFollow`),
  INDEX `fk_Follow_User1_idx` (`idFollower` ASC) VISIBLE,
  INDEX `fk_Follow_User2_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Follow_User1`
    FOREIGN KEY (`idFollower`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Follow_User2`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620
COLLATE = tis620_bin;


-- -----------------------------------------------------
-- Table `mydb`.`FavouriteHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FavouriteHistory` (
  `FavouriteHistoryId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  PRIMARY KEY (`FavouriteHistoryId`),
  INDEX `fk_FavouriteHistory_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_FavouriteHistory_Cafe2_idx` (`CafeId` ASC) VISIBLE,
  CONSTRAINT `fk_FavouriteHistory_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FavouriteHistory_Cafe2`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rating` (
  `CustomerId` INT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `RatingStar` TINYINT NOT NULL,
  `RatingText` TEXT(20) NULL,
  INDEX `fk_Rating_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_Rating_Cafe2_idx` (`CafeId` ASC) VISIBLE,
  PRIMARY KEY (`CustomerId`, `CafeId`),
  CONSTRAINT `fk_Rating_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_Cafe2`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UploadedPhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UploadedPhoto` (
  `idUploadedPhoto` INT NOT NULL,
  `idPhoto` INT NOT NULL,
  `idCafe` INT NOT NULL,
  PRIMARY KEY (`idUploadedPhoto`),
  INDEX `fk_UploadedPhoto_Photo1_idx` (`idPhoto` ASC) VISIBLE,
  INDEX `fk_UploadedPhoto_Cafe1_idx` (`idCafe` ASC) VISIBLE,
  CONSTRAINT `fk_UploadedPhoto_Photo1`
    FOREIGN KEY (`idPhoto`)
    REFERENCES `mydb`.`Photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UploadedPhoto_Cafe1`
    FOREIGN KEY (`idCafe`)
    REFERENCES `mydb`.`Cafe` (`idCafe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620
COLLATE = tis620_bin;


-- -----------------------------------------------------
-- Table `mydb`.`CheckIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CheckIn` (
  `idCheckIn` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idCafe` INT NOT NULL,
  `idTagedUser` INT NULL,
  `checkInTime` DATE NOT NULL,
  PRIMARY KEY (`idCheckIn`),
  INDEX `fk_CheckIn_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_CheckIn_Cafe1_idx` (`idCafe` ASC) VISIBLE,
  INDEX `fk_CheckIn_User2_idx` (`idTagedUser` ASC) VISIBLE,
  CONSTRAINT `fk_CheckIn_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckIn_Cafe1`
    FOREIGN KEY (`idCafe`)
    REFERENCES `mydb`.`Cafe` (`idCafe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckIn_User2`
    FOREIGN KEY (`idTagedUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620
COLLATE = tis620_bin;


-- -----------------------------------------------------
-- Table `mydb`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`News` (
  `NewsId` INT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `Heading` VARCHAR(70) NOT NULL,
  `TextBody` VARCHAR(1000) NOT NULL,
  `NewsPhoto` BLOB NOT NULL,
  `ReleaseTime` DATETIME NOT NULL,
  PRIMARY KEY (`NewsId`),
  INDEX `fk_News_Cafe2_idx` (`CafeId` ASC) VISIBLE,
  UNIQUE INDEX `NewsId_UNIQUE` (`NewsId` ASC) VISIBLE,
  CONSTRAINT `fk_News_Cafe2`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LikeNews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LikeNews` (
  `idLikeNews` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idNews` INT NOT NULL,
  PRIMARY KEY (`idLikeNews`),
  INDEX `fk_LikeNews_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_LikeNews_News1_idx` (`idNews` ASC) VISIBLE,
  CONSTRAINT `fk_LikeNews_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LikeNews_News1`
    FOREIGN KEY (`idNews`)
    REFERENCES `mydb`.`News` (`idNews`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620
COLLATE = tis620_bin;


-- -----------------------------------------------------
-- Table `mydb`.`MenuDrink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MenuDrink` (
  `idDrinkeMenu` INT NOT NULL,
  `idDrink` INT NOT NULL,
  `idMenu` INT NOT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`idDrinkeMenu`),
  INDEX `fk_DrinkeMenu_Drink1_idx` (`idDrink` ASC) VISIBLE,
  INDEX `fk_DrinkeMenu_Menu1_idx` (`idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_DrinkeMenu_Drink1`
    FOREIGN KEY (`idDrink`)
    REFERENCES `mydb`.`Drink` (`idDrink`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DrinkeMenu_Menu1`
    FOREIGN KEY (`idMenu`)
    REFERENCES `mydb`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerId` INT NOT NULL,
  `LoginName` VARCHAR(70) NOT NULL,
  `Password` CHAR(64) NOT NULL,
  `ScreenName` VARCHAR(20) BINARY NOT NULL,
  `PersonalPhoto` BLOB NULL,
  `Gender` CHAR(1) NOT NULL,
  PRIMARY KEY (`CustomerId`),
  UNIQUE INDEX `CustomerId_UNIQUE` (`CustomerId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `LocationId` BIGINT NOT NULL,
  `Longitude` DECIMAL(7,4) NOT NULL,
  `Latitude` DECIMAL(7,4) NOT NULL,
  PRIMARY KEY (`LocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cafe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cafe` (
  `CafeId` SMALLINT NOT NULL,
  `CafeName` VARCHAR(70) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  `LocationId` INT NOT NULL,
  `OpeningHours` TEXT NOT NULL,
  PRIMARY KEY (`CafeId`),
  INDEX `fk_Cafe_Location1_idx` (`LocationId` ASC) VISIBLE,
  CONSTRAINT `fk_Cafe_Location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CurrentLocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CurrentLocation` (
  `CurrentLocationId` BIGINT NOT NULL,
  `CustomerId` INT NOT NULL,
  `LocationId` BIGINT NOT NULL,
  `CurrentTime` DATETIME NOT NULL,
  `BeepStatus` CHAR(1) NOT NULL,
  INDEX `fk_CurrentLocation_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_CurrentLocation_Location1_idx` (`LocationId` ASC) VISIBLE,
  PRIMARY KEY (`CurrentLocationId`),
  UNIQUE INDEX `CurrentLocationId_UNIQUE` (`CurrentLocationId` ASC) VISIBLE,
  CONSTRAINT `fk_CurrentLocation_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CurrentLocation_Location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drink` (
  `DrinkId` TINYINT NOT NULL,
  `DrinkName` VARCHAR(70) NOT NULL,
  `DrinkDescription` VARCHAR(255) NULL,
  PRIMARY KEY (`DrinkId`),
  UNIQUE INDEX `DrinkId_UNIQUE` (`DrinkId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BrewHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BrewHistory` (
  `BrewHistoryId` INT NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `CustomerId` INT NOT NULL,
  `DrinkId` INT NOT NULL,
  PRIMARY KEY (`BrewHistoryId`),
  INDEX `fk_BrewHistory_Drink2_idx` (`DrinkId` ASC) VISIBLE,
  INDEX `fk_BrewHistory_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  UNIQUE INDEX `BrewHistoryId_UNIQUE` (`BrewHistoryId` ASC) VISIBLE,
  CONSTRAINT `fk_BrewHistory_Drink2`
    FOREIGN KEY (`DrinkId`)
    REFERENCES `mydb`.`Drink` (`DrinkId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BrewHistory_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FollowRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FollowRecord` (
  `FollowRecordId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  `FollowerId` INT NOT NULL,
  `Status` CHAR(1) NOT NULL,
  `OperationTime` DATETIME NOT NULL,
  PRIMARY KEY (`FollowRecordId`),
  INDEX `fk_FollowRecord_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_FollowRecord_Customer2_idx` (`FollowerId` ASC) VISIBLE,
  UNIQUE INDEX `FollowRecordId_UNIQUE` (`FollowRecordId` ASC) VISIBLE,
  CONSTRAINT `fk_FollowRecord_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FollowRecord_Customer2`
    FOREIGN KEY (`FollowerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FavouriteHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FavouriteHistory` (
  `FavouriteHistoryId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  PRIMARY KEY (`FavouriteHistoryId`),
  INDEX `fk_FavouriteHistory_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_FavouriteHistory_Cafe2_idx` (`CafeId` ASC) VISIBLE,
  CONSTRAINT `fk_FavouriteHistory_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FavouriteHistory_Cafe2`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rating` (
  `CustomerId` INT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `RatingStar` TINYINT NOT NULL,
  `RatingText` TEXT(20) NULL,
  INDEX `fk_Rating_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_Rating_Cafe2_idx` (`CafeId` ASC) VISIBLE,
  PRIMARY KEY (`CustomerId`, `CafeId`),
  CONSTRAINT `fk_Rating_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_Cafe2`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `PostId` BIGINT NOT NULL,
  `PostText` VARCHAR(1000) NOT NULL,
  `PostPhoto` BLOB NULL,
  `PostTime` DATETIME NOT NULL,
  PRIMARY KEY (`PostId`),
  UNIQUE INDEX `PostId_UNIQUE` (`PostId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PostComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PostComment` (
  `CommenrId` BIGINT NOT NULL,
  `PostId` BIGINT NOT NULL,
  `CommentText` VARCHAR(1000) NOT NULL,
  `CommentCustomerId` INT NULL,
  PRIMARY KEY (`CommenrId`),
  INDEX `fk_CommentPost_Post2_idx` (`PostId` ASC) VISIBLE,
  INDEX `fk_CommentPost_Customer1_idx` (`CommentCustomerId` ASC) VISIBLE,
  UNIQUE INDEX `CommenrId_UNIQUE` (`CommenrId` ASC) VISIBLE,
  CONSTRAINT `fk_CommentPost_Post2`
    FOREIGN KEY (`PostId`)
    REFERENCES `mydb`.`Post` (`PostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CommentPost_Customer1`
    FOREIGN KEY (`CommentCustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CheckInRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CheckInRecord` (
  `CheckInRecordId` BIGINT NOT NULL,
  `CustomerId` INT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `CheckInTime` DATETIME NOT NULL,
  `TagedCustomerId` INT NULL,
  PRIMARY KEY (`CheckInRecordId`),
  INDEX `fk_CheckInRecord_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_CheckInRecord_Cafe1_idx` (`CafeId` ASC) VISIBLE,
  INDEX `fk_CheckInRecord_Customer2_idx` (`TagedCustomerId` ASC) VISIBLE,
  UNIQUE INDEX `CheckInRecordId_UNIQUE` (`CheckInRecordId` ASC) VISIBLE,
  CONSTRAINT `fk_CheckInRecord_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckInRecord_Cafe1`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckInRecord_Customer2`
    FOREIGN KEY (`TagedCustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`News` (
  `NewsId` INT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `Heading` VARCHAR(70) NOT NULL,
  `TextBody` VARCHAR(1000) NOT NULL,
  `NewsPhoto` BLOB NOT NULL,
  `ReleaseTime` DATETIME NOT NULL,
  PRIMARY KEY (`NewsId`),
  INDEX `fk_News_Cafe2_idx` (`CafeId` ASC) VISIBLE,
  UNIQUE INDEX `NewsId_UNIQUE` (`NewsId` ASC) VISIBLE,
  CONSTRAINT `fk_News_Cafe2`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CafePhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CafePhoto` (
  `CafePhotoId` MEDIUMINT NOT NULL,
  `CafeId` SMALLINT NOT NULL,
  `UploadedPhoto` BLOB NOT NULL,
  `UploadedTime` DATETIME NOT NULL,
  INDEX `fk_Cafe_has_UploadPhoto_Cafe1_idx` (`CafeId` ASC) VISIBLE,
  PRIMARY KEY (`CafePhotoId`),
  UNIQUE INDEX `CafePhotoId_UNIQUE` (`CafePhotoId` ASC) VISIBLE,
  UNIQUE INDEX `UploadedPhoto_UNIQUE` (`UploadedPhoto` ASC) VISIBLE,
  CONSTRAINT `fk_Cafe_has_UploadPhoto_Cafe1`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_like_Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_like_Post` (
  `CustomerId` INT NOT NULL,
  `PostId` BIGINT NOT NULL,
  `LikeStatus` CHAR(1) NOT NULL,
  PRIMARY KEY (`CustomerId`, `PostId`),
  INDEX `fk_Customer_has_Post_Post1_idx` (`PostId` ASC) VISIBLE,
  INDEX `fk_Customer_has_Post_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Post_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Post_Post1`
    FOREIGN KEY (`PostId`)
    REFERENCES `mydb`.`Post` (`PostId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_like_News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_like_News` (
  `CustomerId` INT NOT NULL,
  `NewsId` INT NOT NULL,
  `LikeStatus` CHAR(1) NOT NULL,
  PRIMARY KEY (`CustomerId`, `NewsId`),
  INDEX `fk_Customer_has_News_News1_idx` (`NewsId` ASC) VISIBLE,
  INDEX `fk_Customer_has_News_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_News_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_News_News1`
    FOREIGN KEY (`NewsId`)
    REFERENCES `mydb`.`News` (`NewsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `CafeId` SMALLINT NOT NULL,
  `DrinkId` TINYINT NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CafeId`, `DrinkId`),
  INDEX `fk_Cafe_has_Drink_Drink1_idx` (`DrinkId` ASC) VISIBLE,
  INDEX `fk_Cafe_has_Drink_Cafe1_idx` (`CafeId` ASC) VISIBLE,
  CONSTRAINT `fk_Cafe_has_Drink_Cafe1`
    FOREIGN KEY (`CafeId`)
    REFERENCES `mydb`.`Cafe` (`CafeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cafe_has_Drink_Drink1`
    FOREIGN KEY (`DrinkId`)
    REFERENCES `mydb`.`Drink` (`DrinkId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
